// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"display: flex; align-items: start;\"><span class=\"circle\" style=\"background-color: oklch(0.9 0.01 230.85);\" data-lightness=\"0.9\" data-chroma=\"0.01\"></span> <span class=\"circle\" style=\"background-color: oklch(0.9 0.03 230.85);\" data-lightness=\"0.9\" data-chroma=\"0.03\"></span> <span class=\"circle\" style=\"background-color: oklch(0.9 0.045 230.85);\" data-lightness=\"0.9\" data-chroma=\"0.045\"></span> <span class=\"circle\" style=\"background-color: oklch(0.9 0.06 230.85);\" data-lightness=\"0.9\" data-chroma=\"0.06\"></span> <a target=\"_blank\" href=\"https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/oklch\" style=\"color:oklch(0.7671 0.0031 78.2); font-size:0.8rem; text-decoration: none; padding-top: 0.3rem; padding-left: 0.3rem;\">what's this?</a></div><br><div class=\"top\"><div><a href=\"mailto:andrea@fresneda.digital\" style=\"text-decoration: underline; color: oklch(0 0 0 / 10%);\"><h1 style=\"color: black;\">Andrea<span class=\"inria-sans-regular\" style=\"color:oklch(0 0 0 / 10%); font-size: clamp(1rem, 2vw + 1rem, 3rem);\">&commat;fresneda.digital</span></h1></a><h2 class=\"inria-serif-bold\" style=\"margin-top: 0\">Full-stack Software Engineer</h2></div><p class=\"inria-sans-regular\" style=\"font-size: 1.2rem;\">Creating user-centric solutions that bridge the gap between complex technical concepts and real-world use cases.</p></div><div class=\"inria-sans-light description-box\">🇪🇸 Madrid, Spain / 🇬🇧 London, UK</div><br><script>\n\t\tdocument.querySelectorAll('.circle').forEach(circle => {\n\t\t\tcircle.addEventListener('click', function() {\n\t\t\t\tconst lightness = this.dataset.lightness;\n\t\t\t\tconst chroma = this.dataset.chroma;\n\t\t\t\tconst randomHue = Math.floor(Math.random() * 361);\n\t\t\t\tthis.style.backgroundColor = `oklch(${lightness} ${chroma} ${randomHue})`;\n\t\t\t});\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
